version: "3.9"
services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  rubysidekiq:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/usr/src/ruby
    ports:
      - "3000:3000"
    depends_on:
      - redis
volumes:
  ruby:

